version: "3.9"
services:
  poutine:
    build:
      context: ./poutine
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./poutine:/app
    container_name: poutine
  plantain:
    build:
      context: ./plantain
      dockerfile: Dockerfile
    ports:
      - "3070:3070"
    volumes:
      - ./plantain:/app
    container_name: plantain
  database:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    container_name: venddb
